use mydatabase;
select city, address,count(city) from studentdetails
where city in('Pune','Amravati','Nagpur')
group by city,address
having count(city) >1;

use mydatabase;
select * from studentdetails;
insert into studentdetails values('70','Atharva','xy road','Nagpur',7678768);


#1. Retrieve the total revenue generated for each film category.

use sakila;

select c.category_id,sum(p.amount) from category c
join film_category c2 on c.category_id=c2.category_id 
join film f on f.film_id=c2.film_id
join inventory i on i.film_id=f.film_id
join rental r on r.inventory_id=i.inventory_id
join payment p on p.rental_id=r.rental_id	
group by c.category_id;



#2. Determine the count of rentals for each customer.

select count(rental_id)
from customer c
join rental r on c.customer_id=r.customer_id
group by c.customer_id
order by c.customer_id;

#3. Calculate the average rental duration (in days) for each film.

select film_id,avg(rental_duration)
from film 
group by film_id;

#4. Find the total revenue generated for each month.

select date_format(payment_date,'%m') as months, sum(amount)
from payment p
group by months;

#5. Determine the total revenue generated by each store.

select s.store_id,sum(p.amount)
from store s
join staff s1 on s.store_id=s1.store_id
join rental r on r.staff_id=s1.staff_id
join payment p on p.rental_id=r.rental_id
group by s.store_id
order by sum(p.amount);

#6. Calculate the count of rentals handled by each staff member.

select st.staff_id,count(r.rental_id) as rental_count
from staff st
join rental r on st.staff_id = r.staff_id
group by st.staff_id
order by rental_count desc;

#7. Compute the average rental rate for each film category.

select c.category_id,avg(rental_rate) from category c
join film_category c2 on c.category_id=c2.category_id 
join film f on f.film_id=c2.film_id
join inventory i on i.film_id=f.film_id
join rental r on r.inventory_id=i.inventory_id
group by c.category_id;

#8. Determine the count of rentals for each film.
use sakila;
select f.title,count(r.rental_id) as rental
from rental r
join inventory i on i.inventory_id=r.inventory_id
join film f on f.film_id=i.film_id
group by f.title
order by rental desc;

#9. Retrieve the total revenue generated for each city.

select c.city_id,sum(p.amount) as amount
from address a
join city c on c.city_id=a.city_id
join staff s on a.address_id=s.address_id
join payment p on s.staff_id=p.staff_id
group by c.city_id
order by amount;

#10. Calculate the count of rentals for each film language.

select l.name, count(r.rental_id)
from rental r
join inventory i on r.inventory_id=i.inventory_id
join film f on f.film_id=i.film_id
join language l on l.language_id=f.language_id
group by l.name

